### ISSUE TITLE
lcd_i2c.c gives error

### ISSUE THREAD

**Issue by phy-zik-tschie** [matejkrenek/stm8-lcd-i2c#1]
MCU: stm8s003f3p6
ToolSet: Stm8Cosmic
Compiler: STVD
Windows 11

Compiling src\lcd_i2c.c...
cxstm8 -iinc +debug -pxp -no -l +mods0 -pp -i"C:\Program Files (x86)\COSMIC\Hstm8"  -clDebug\ -coDebug\ src\lcd_i2c.c 
**#error cpstm8 src\lcd_i2c.c:39(19) missing prototype
#error cpstm8 src\lcd_i2c.c:40(17) missing prototype
#error cpstm8 src\lcd_i2c.c:43(16) missing prototype
#error cpstm8 src\lcd_i2c.c:136(8) missing ;
#error cpstm8 src\lcd_i2c.c:136(20) i undefined**
src\lcd_i2c.c:
 **The command: "cxstm8 -iinc +debug -pxp -no -l +mods0 -pp -i"C:\Program Files (x86)\COSMIC\Hstm8"  -clDebug\ -coDebug\ src\lcd_i2c.c " has failed, the returned value is: 1**
exit code=1.

radyo.elf - 7 error(s), 0 warning(s)

**Comment by matejkrenek** [comment]
Do you have the `lcd_i2c.h` file included when compiling the project, because it seems that prototypes of the LCD_I2C functions are not included and therefor the `missing prototype` error shows up?

**Comment by phy-zik-tschie** [comment]
There is no problem when compiling with iar.

**To compile with stvd, the function called should not be below. For a function that does not have a variable, the expression "void" should be added.**

![Ekran görüntüsü 2024-07-24 055820](https://github.com/user-attachments/assets/cdc43f81-ab22-47a1-af0f-4bb169cf98df)

**Also, the i variable should be defined before for.**

![Ekran görüntüsü 2024-07-24 060536](https://github.com/user-attachments/assets/24aef7b9-e044-4929-adfc-4ec1858c5d35)
